//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Archivos
    {
        public int id_documento_notaria { get; set; }
        public int id_notaria { get; set; }
        public int id_solicitud_notaria { get; set; }
        public string nombre_archivo { get; set; }
        public string direccion_documento { get; set; }
        public System.DateTime fecha_subida { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Catalogo_Operaciones
    {
        public int id_Catalogo_Tipo_Operacion { get; set; }
        public int id_Catalogo_Tipo_Manifiesto { get; set; }
        public string nombre_Operacion { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Catalogo_Tipos_Terrenos
    {
        public int id_Catalogo_Tipo_Terreno { get; set; }
        public string nombre_Tipo_Terreno { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Catalogo_Usos_Terrenos_Rurales
    {
        public int id_Catalogo_Uso_Terreno_Rural { get; set; }
        public string nombre_Uso_Terreno_Rural { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Catalogo_Usos_Terrenos_Urbanos
    {
        public int id_Catalogo_Uso_Terreno_Urbano { get; set; }
        public string nombre_Uso_Terreno_Urbano { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Colindancias
    {
        public int id_Colindancia { get; set; }
        public int id_Solicitud_Notaria { get; set; }
        public int id_Solicitud_Predio { get; set; }
        public string punto_Cardinal { get; set; }
        public Nullable<decimal> distancia_Metros { get; set; }
        public string colindancias { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Solicitudes_Domicilio_Notificacion
    {
        public int id_Solicitud_Domicilio_Notificacion { get; set; }
        public int id_Solicitud_Notaria { get; set; }
        public string calle { get; set; }
        public string numero_Oficial { get; set; }
        public string colonia { get; set; }
        public string poblacion { get; set; }
        public string codigo_Postal { get; set; }
        public string estado { get; set; }
        public string rfc { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Solicitudes_Notarias
    {
        public int id_Solicitud_Notaria { get; set; }
        public int id_Catalogo_Notaria { get; set; }
        public int id_Estatus_Solicitud { get; set; }
        public int id_Catalogo_Usuario_Notaria { get; set; }
        public int id_Catalogo_Tipo_Manifiesto { get; set; }
        public int id_Catalogo_Tipo_Operacion { get; set; }
        public int folio_Solicitud_Notaria { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public string oficina_Ubicacion { get; set; }
        public string codigo_Postal { get; set; }
        public string clave_Catastral_Vendedor { get; set; }
        public string curp_Vendedor { get; set; }
        public string clave_Catastral_Comprador { get; set; }
        public string curp_Comprador { get; set; }
        public string numero_Autorizacion { get; set; }
        public string tipo_Documento { get; set; }
        public string numero { get; set; }
        public string volumen { get; set; }
        public Nullable<System.DateTime> fecha_Documento { get; set; }
        public Nullable<decimal> precio_Pactado { get; set; }
        public Nullable<decimal> avaluo_Comercial { get; set; }
        public Nullable<decimal> valor_Base_Impuesto { get; set; }
        public Nullable<decimal> deduccion { get; set; }
        public Nullable<decimal> base_gravable { get; set; }
        public Nullable<decimal> impuesto_base { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> recargos { get; set; }
        public string poblacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> total { get; set; }
        public bool cancelado { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Solicitudes_Predios
    {
        public int id_Solicitud_Predio { get; set; }
        public int id_Solicitud_Notaria { get; set; }
        public int id_Catalogo_Tipo_Terreno { get; set; }
        public int id_Catalogo_Uso_Terreno { get; set; }
        public int id_Catalogo_Tipo_Operacion { get; set; }
        public int tipo_Origen_Destino { get; set; }
        public string clave_Catastral_Predio { get; set; }
        public string municipio { get; set; }
        public string poblacion { get; set; }
        public string calle { get; set; }
        public string numero_Oficial { get; set; }
        public string colonia { get; set; }
        public string codigo_Postal { get; set; }
        public string numero_Lote { get; set; }
        public string numero_Manzana { get; set; }
        public Nullable<decimal> superficie_Terreno { get; set; }
        public string otro_Uso_Terreno { get; set; }
        public Nullable<decimal> valor_Catastral { get; set; }
        public string nombre_predio { get; set; }
        public string poblacion_cercana { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Solicitudes_Propietarios
    {
        public int id_Solicitud_Propietario { get; set; }
        public int id_Solicitud_Notaria { get; set; }
        public int id_Tipo_Propietario { get; set; }
        public string nombre_Razon_Social { get; set; }
        public string curp { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public int tipo_Propietario_Transmite_Adquiere { get; set; }
    }
}
namespace Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catastro_Solicitudes_Uso_Terreno_Rural
    {
        public int id_Solicitud_Uso_Terreno_Rural { get; set; }
        public int id_Solicitud_Notaria { get; set; }
        public int id_Catalogo_Clase_Terreno_Rural { get; set; }
        public Nullable<decimal> superficie_Hectareas { get; set; }
    }
}
