//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_Catastros_Entities : DbContext
    {
        public db_Catastros_Entities()
            : base("name=db_Catastros_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catastro_Archivos> Catastro_Archivos { get; set; }
        public virtual DbSet<Catastro_Catalogo_Operaciones> Catastro_Catalogo_Operaciones { get; set; }
        public virtual DbSet<Catastro_Catalogo_Tipos_Terrenos> Catastro_Catalogo_Tipos_Terrenos { get; set; }
        public virtual DbSet<Catastro_Catalogo_Usos_Terrenos_Rurales> Catastro_Catalogo_Usos_Terrenos_Rurales { get; set; }
        public virtual DbSet<Catastro_Catalogo_Usos_Terrenos_Urbanos> Catastro_Catalogo_Usos_Terrenos_Urbanos { get; set; }
        public virtual DbSet<Catastro_Colindancias> Catastro_Colindancias { get; set; }
        public virtual DbSet<Catastro_Solicitudes_Domicilio_Notificacion> Catastro_Solicitudes_Domicilio_Notificacion { get; set; }
        public virtual DbSet<Catastro_Solicitudes_Predios> Catastro_Solicitudes_Predios { get; set; }
        public virtual DbSet<Catastro_Solicitudes_Propietarios> Catastro_Solicitudes_Propietarios { get; set; }
        public virtual DbSet<Catastro_Solicitudes_Uso_Terreno_Rural> Catastro_Solicitudes_Uso_Terreno_Rural { get; set; }
        public virtual DbSet<Catastro_Solicitudes_Notarias> Catastro_Solicitudes_Notarias { get; set; }
    }
}
